//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5 C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g 2023-05-16 20:22:14

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using Neo;
using System;
using System.Collections.Generic;


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5")]
[System.CLSCompliant(false)]
public partial class NeoTreePass1 : Antlr.Runtime.Tree.TreeParser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "ASSIGNMENT", "COMMENT", "DECLARATION", "FILE", "FLOAT_VALUE", "FUNCTION_ARGUMENT", "FUNCTION_ARGUMENTS", "FUNCTION_BODY", "FUNCTION_CALL", "FUNCTION_DEF", "FUNCTION_DEFS", "ID", "INT_VALUE", "LITERAL", "PARAM", "PARAMS", "PARENEXP", "PROGRAM", "SCRIPT", "TYPE_FLOAT", "TYPE_INT", "UNARY", "VARIABLE", "WS", "'('", "')'", "'*'", "'+'", "','", "'-'", "'/'", "';'", "'='", "'{'", "'}'", "FLOAT", "INT"
	};
	public const int EOF=-1;
	public const int T__28=28;
	public const int T__29=29;
	public const int T__30=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int T__33=33;
	public const int T__34=34;
	public const int T__35=35;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int ASSIGNMENT=4;
	public const int COMMENT=5;
	public const int DECLARATION=6;
	public const int FILE=7;
	public const int FLOAT_VALUE=8;
	public const int FUNCTION_ARGUMENT=9;
	public const int FUNCTION_ARGUMENTS=10;
	public const int FUNCTION_BODY=11;
	public const int FUNCTION_CALL=12;
	public const int FUNCTION_DEF=13;
	public const int FUNCTION_DEFS=14;
	public const int ID=15;
	public const int INT_VALUE=16;
	public const int LITERAL=17;
	public const int PARAM=18;
	public const int PARAMS=19;
	public const int PARENEXP=20;
	public const int PROGRAM=21;
	public const int SCRIPT=22;
	public const int TYPE_FLOAT=23;
	public const int TYPE_INT=24;
	public const int UNARY=25;
	public const int VARIABLE=26;
	public const int WS=27;
	public const int FLOAT=39;
	public const int INT=40;

	public NeoTreePass1(ITreeNodeStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public NeoTreePass1(ITreeNodeStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}

	public override string[] TokenNames { get { return NeoTreePass1.tokenNames; } }
	public override string GrammarFileName { get { return "C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g"; } }


	public void	Process() {
			file();
		}


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_file();
	partial void LeaveRule_file();
	// $ANTLR start "file"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:22:1: file : (| ^( FILE script ) );
	[GrammarRule("file")]
	private void file()
	{
		EnterRule_file();
		EnterRule("file", 1);
		TraceIn("file", 1);
		try { DebugEnterRule(GrammarFileName, "file");
		DebugLocation(22, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:22:6: (| ^( FILE script ) )
			int alt1=2;
			try { DebugEnterDecision(1, false);
			int LA1_1 = input.LA(1);

			if ((LA1_1==EOF))
			{
				alt1 = 1;
			}
			else if ((LA1_1==FILE))
			{
				alt1 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 1, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:23:2: 
				{
				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:23:4: ^( FILE script )
				{
				DebugLocation(23, 4);
				DebugLocation(23, 6);
				Match(input,FILE,Follow._FILE_in_file54); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(23, 11);
				PushFollow(Follow._script_in_file56);
				script();
				PopFollow();


				Match(input, TokenTypes.Up, null); 


				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("file", 1);
			LeaveRule("file", 1);
			LeaveRule_file();
		}
		DebugLocation(24, 1);
		} finally { DebugExitRule(GrammarFileName, "file"); }
		return;

	}
	// $ANTLR end "file"

	partial void EnterRule_script();
	partial void LeaveRule_script();
	// $ANTLR start "script"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:26:1: script : ( ^( SCRIPT functionDefs ( program )? ) | ^( SCRIPT program ) );
	[GrammarRule("script")]
	private void script()
	{
		EnterRule_script();
		EnterRule("script", 2);
		TraceIn("script", 2);
		try { DebugEnterRule(GrammarFileName, "script");
		DebugLocation(26, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:26:9: ( ^( SCRIPT functionDefs ( program )? ) | ^( SCRIPT program ) )
			int alt3=2;
			try { DebugEnterDecision(3, false);
			int LA3_1 = input.LA(1);

			if ((LA3_1==SCRIPT))
			{
				int LA3_2 = input.LA(2);

				if ((LA3_2==DOWN))
				{
					int LA3_3 = input.LA(3);

					if ((LA3_3==FUNCTION_DEFS))
					{
						alt3 = 1;
					}
					else if ((LA3_3==PROGRAM))
					{
						alt3 = 2;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 3, 2, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 3, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 3, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:26:11: ^( SCRIPT functionDefs ( program )? )
				{
				DebugLocation(26, 11);
				DebugLocation(26, 13);
				Match(input,SCRIPT,Follow._SCRIPT_in_script70); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(26, 20);
				PushFollow(Follow._functionDefs_in_script72);
				functionDefs();
				PopFollow();

				DebugLocation(26, 33);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:26:33: ( program )?
				int alt2=2;
				try { DebugEnterSubRule(2);
				try { DebugEnterDecision(2, false);
				int LA2_1 = input.LA(1);

				if ((LA2_1==PROGRAM))
				{
					alt2 = 1;
				}
				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:26:34: program
					{
					DebugLocation(26, 34);
					PushFollow(Follow._program_in_script75);
					program();
					PopFollow();


					}
					break;

				}
				} finally { DebugExitSubRule(2); }


				Match(input, TokenTypes.Up, null); 

				DebugLocation(26, 45);


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:27:4: ^( SCRIPT program )
				{
				DebugLocation(27, 4);
				DebugLocation(27, 6);
				Match(input,SCRIPT,Follow._SCRIPT_in_script86); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(27, 13);
				PushFollow(Follow._program_in_script88);
				program();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(27, 22);


				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("script", 2);
			LeaveRule("script", 2);
			LeaveRule_script();
		}
		DebugLocation(28, 1);
		} finally { DebugExitRule(GrammarFileName, "script"); }
		return;

	}
	// $ANTLR end "script"

	partial void EnterRule_functionDefs();
	partial void LeaveRule_functionDefs();
	// $ANTLR start "functionDefs"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:30:1: functionDefs : ^( FUNCTION_DEFS ( functionDef )+ ) ;
	[GrammarRule("functionDefs")]
	private void functionDefs()
	{
		EnterRule_functionDefs();
		EnterRule("functionDefs", 3);
		TraceIn("functionDefs", 3);
		try { DebugEnterRule(GrammarFileName, "functionDefs");
		DebugLocation(30, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:31:2: ( ^( FUNCTION_DEFS ( functionDef )+ ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:31:4: ^( FUNCTION_DEFS ( functionDef )+ )
			{
			DebugLocation(31, 4);
			DebugLocation(31, 6);
			Match(input,FUNCTION_DEFS,Follow._FUNCTION_DEFS_in_functionDefs104); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(31, 20);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:31:20: ( functionDef )+
			int cnt4=0;
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, false);
				int LA4_1 = input.LA(1);

				if ((LA4_1==FUNCTION_DEF))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:31:20: functionDef
					{
					DebugLocation(31, 20);
					PushFollow(Follow._functionDef_in_functionDefs106);
					functionDef();
					PopFollow();


					}
					break;

				default:
					if (cnt4 >= 1)
						goto loop4;

					EarlyExitException eee4 = new EarlyExitException( 4, input );
					DebugRecognitionException(eee4);
					throw eee4;
				}
				cnt4++;
			}
			loop4:
				;

			} finally { DebugExitSubRule(4); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("functionDefs", 3);
			LeaveRule("functionDefs", 3);
			LeaveRule_functionDefs();
		}
		DebugLocation(32, 1);
		} finally { DebugExitRule(GrammarFileName, "functionDefs"); }
		return;

	}
	// $ANTLR end "functionDefs"

	partial void EnterRule_functionDef();
	partial void LeaveRule_functionDef();
	// $ANTLR start "functionDef"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:34:1: functionDef : ^( FUNCTION_DEF f= ID (c= parameters )? (numDecls= body )? ) ;
	[GrammarRule("functionDef")]
	private void functionDef()
	{
		EnterRule_functionDef();
		EnterRule("functionDef", 4);
		TraceIn("functionDef", 4);
		CommonTree f = default(CommonTree);
		int c = default(int);
		int numDecls = default(int);


			int 	numParams = 0;
			int	stackFrameSize = 0;

		try { DebugEnterRule(GrammarFileName, "functionDef");
		DebugLocation(34, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:39:2: ( ^( FUNCTION_DEF f= ID (c= parameters )? (numDecls= body )? ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:39:4: ^( FUNCTION_DEF f= ID (c= parameters )? (numDecls= body )? )
			{
			DebugLocation(39, 4);
			DebugLocation(39, 6);
			Match(input,FUNCTION_DEF,Follow._FUNCTION_DEF_in_functionDef126); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(39, 20);
			f=(CommonTree)Match(input,ID,Follow._ID_in_functionDef130); 
			DebugLocation(39, 24);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:39:24: (c= parameters )?
			int alt5=2;
			try { DebugEnterSubRule(5);
			try { DebugEnterDecision(5, false);
			int LA5_1 = input.LA(1);

			if ((LA5_1==PARAMS))
			{
				alt5 = 1;
			}
			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:39:25: c= parameters
				{
				DebugLocation(39, 26);
				PushFollow(Follow._parameters_in_functionDef135);
				c=parameters();
				PopFollow();

				DebugLocation(39, 38);
				numParams = c;

				}
				break;

			}
			} finally { DebugExitSubRule(5); }

			DebugLocation(39, 57);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:39:57: (numDecls= body )?
			int alt6=2;
			try { DebugEnterSubRule(6);
			try { DebugEnterDecision(6, false);
			int LA6_1 = input.LA(1);

			if ((LA6_1==FUNCTION_BODY))
			{
				alt6 = 1;
			}
			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:39:58: numDecls= body
				{
				DebugLocation(39, 66);
				PushFollow(Follow._body_in_functionDef144);
				numDecls=body();
				PopFollow();

				DebugLocation(39, 72);
				stackFrameSize = numDecls;

				}
				break;

			}
			} finally { DebugExitSubRule(6); }


			Match(input, TokenTypes.Up, null); 

			DebugLocation(39, 104);
			 ProgramDef.Instance.FunctionDefs.Create((f!=null?f.Text:default(string)), numParams, stackFrameSize); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("functionDef", 4);
			LeaveRule("functionDef", 4);
			LeaveRule_functionDef();
		}
		DebugLocation(40, 1);
		} finally { DebugExitRule(GrammarFileName, "functionDef"); }
		return;

	}
	// $ANTLR end "functionDef"

	partial void EnterRule_body();
	partial void LeaveRule_body();
	// $ANTLR start "body"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:42:1: body returns [int retNumDeclarations] : ^( FUNCTION_BODY (s= statement )+ ) ;
	[GrammarRule("body")]
	private int body()
	{
		EnterRule_body();
		EnterRule("body", 5);
		TraceIn("body", 5);
		int retNumDeclarations = default(int);


		int s = default(int);


			int numDecls = 0;

		try { DebugEnterRule(GrammarFileName, "body");
		DebugLocation(42, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:46:2: ( ^( FUNCTION_BODY (s= statement )+ ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:46:4: ^( FUNCTION_BODY (s= statement )+ )
			{
			DebugLocation(46, 4);
			DebugLocation(46, 6);
			Match(input,FUNCTION_BODY,Follow._FUNCTION_BODY_in_body172); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(46, 20);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:46:20: (s= statement )+
			int cnt7=0;
			try { DebugEnterSubRule(7);
			while (true)
			{
				int alt7=2;
				try { DebugEnterDecision(7, false);
				int LA7_1 = input.LA(1);

				if ((LA7_1==ASSIGNMENT||LA7_1==DECLARATION||LA7_1==FUNCTION_CALL))
				{
					alt7 = 1;
				}


				} finally { DebugExitDecision(7); }
				switch (alt7)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:46:21: s= statement
					{
					DebugLocation(46, 22);
					PushFollow(Follow._statement_in_body177);
					s=statement();
					PopFollow();

					DebugLocation(46, 33);
					 numDecls += s; 

					}
					break;

				default:
					if (cnt7 >= 1)
						goto loop7;

					EarlyExitException eee7 = new EarlyExitException( 7, input );
					DebugRecognitionException(eee7);
					throw eee7;
				}
				cnt7++;
			}
			loop7:
				;

			} finally { DebugExitSubRule(7); }


			Match(input, TokenTypes.Up, null); 

			DebugLocation(46, 55);
			 retNumDeclarations = numDecls; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("body", 5);
			LeaveRule("body", 5);
			LeaveRule_body();
		}
		DebugLocation(47, 1);
		} finally { DebugExitRule(GrammarFileName, "body"); }
		return retNumDeclarations;

	}
	// $ANTLR end "body"

	partial void EnterRule_parameters();
	partial void LeaveRule_parameters();
	// $ANTLR start "parameters"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:49:1: parameters returns [int retNumParams] : ^( PARAMS ( param )+ ) ;
	[GrammarRule("parameters")]
	private int parameters()
	{
		EnterRule_parameters();
		EnterRule("parameters", 6);
		TraceIn("parameters", 6);
		int retNumParams = default(int);



			int numParams = 0;

		try { DebugEnterRule(GrammarFileName, "parameters");
		DebugLocation(49, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:56:2: ( ^( PARAMS ( param )+ ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:56:4: ^( PARAMS ( param )+ )
			{
			DebugLocation(56, 4);
			DebugLocation(56, 6);
			Match(input,PARAMS,Follow._PARAMS_in_parameters210); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(56, 13);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:56:13: ( param )+
			int cnt8=0;
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_1 = input.LA(1);

				if ((LA8_1==PARAM))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch (alt8)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:56:14: param
					{
					DebugLocation(56, 14);
					PushFollow(Follow._param_in_parameters213);
					param();
					PopFollow();

					DebugLocation(56, 20);
					++numParams;

					}
					break;

				default:
					if (cnt8 >= 1)
						goto loop8;

					EarlyExitException eee8 = new EarlyExitException( 8, input );
					DebugRecognitionException(eee8);
					throw eee8;
				}
				cnt8++;
			}
			loop8:
				;

			} finally { DebugExitSubRule(8); }


			Match(input, TokenTypes.Up, null); 


			}


				retNumParams = numParams;

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("parameters", 6);
			LeaveRule("parameters", 6);
			LeaveRule_parameters();
		}
		DebugLocation(57, 1);
		} finally { DebugExitRule(GrammarFileName, "parameters"); }
		return retNumParams;

	}
	// $ANTLR end "parameters"

	partial void EnterRule_param();
	partial void LeaveRule_param();
	// $ANTLR start "param"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:59:1: param : ^( PARAM ID ID ) ;
	[GrammarRule("param")]
	private void param()
	{
		EnterRule_param();
		EnterRule("param", 7);
		TraceIn("param", 7);
		try { DebugEnterRule(GrammarFileName, "param");
		DebugLocation(59, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:60:2: ( ^( PARAM ID ID ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:60:4: ^( PARAM ID ID )
			{
			DebugLocation(60, 4);
			DebugLocation(60, 6);
			Match(input,PARAM,Follow._PARAM_in_param231); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(60, 12);
			Match(input,ID,Follow._ID_in_param233); 
			DebugLocation(60, 15);
			Match(input,ID,Follow._ID_in_param235); 

			Match(input, TokenTypes.Up, null); 

			DebugLocation(60, 19);
			 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("param", 7);
			LeaveRule("param", 7);
			LeaveRule_param();
		}
		DebugLocation(61, 1);
		} finally { DebugExitRule(GrammarFileName, "param"); }
		return;

	}
	// $ANTLR end "param"

	partial void EnterRule_functionCall();
	partial void LeaveRule_functionCall();
	// $ANTLR start "functionCall"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:65:1: functionCall : ^( FUNCTION_CALL f= ID ( arguments )? ) ;
	[GrammarRule("functionCall")]
	private void functionCall()
	{
		EnterRule_functionCall();
		EnterRule("functionCall", 8);
		TraceIn("functionCall", 8);
		CommonTree f = default(CommonTree);

		try { DebugEnterRule(GrammarFileName, "functionCall");
		DebugLocation(65, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:66:2: ( ^( FUNCTION_CALL f= ID ( arguments )? ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:66:4: ^( FUNCTION_CALL f= ID ( arguments )? )
			{
			DebugLocation(66, 4);
			DebugLocation(66, 6);
			Match(input,FUNCTION_CALL,Follow._FUNCTION_CALL_in_functionCall254); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(66, 21);
			f=(CommonTree)Match(input,ID,Follow._ID_in_functionCall258); 
			DebugLocation(66, 25);

			DebugLocation(66, 28);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:66:28: ( arguments )?
			int alt9=2;
			try { DebugEnterSubRule(9);
			try { DebugEnterDecision(9, false);
			int LA9_1 = input.LA(1);

			if ((LA9_1==FUNCTION_ARGUMENTS))
			{
				alt9 = 1;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:66:28: arguments
				{
				DebugLocation(66, 28);
				PushFollow(Follow._arguments_in_functionCall262);
				arguments();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(9); }


			Match(input, TokenTypes.Up, null); 

			DebugLocation(66, 40);

				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("functionCall", 8);
			LeaveRule("functionCall", 8);
			LeaveRule_functionCall();
		}
		DebugLocation(68, 1);
		} finally { DebugExitRule(GrammarFileName, "functionCall"); }
		return;

	}
	// $ANTLR end "functionCall"

	partial void EnterRule_arguments();
	partial void LeaveRule_arguments();
	// $ANTLR start "arguments"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:70:1: arguments : ^( FUNCTION_ARGUMENTS ( argument )+ ) ;
	[GrammarRule("arguments")]
	private void arguments()
	{
		EnterRule_arguments();
		EnterRule("arguments", 9);
		TraceIn("arguments", 9);
		try { DebugEnterRule(GrammarFileName, "arguments");
		DebugLocation(70, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:71:2: ( ^( FUNCTION_ARGUMENTS ( argument )+ ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:71:4: ^( FUNCTION_ARGUMENTS ( argument )+ )
			{
			DebugLocation(71, 4);
			DebugLocation(71, 6);
			Match(input,FUNCTION_ARGUMENTS,Follow._FUNCTION_ARGUMENTS_in_arguments279); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(71, 25);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:71:25: ( argument )+
			int cnt10=0;
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=2;
				try { DebugEnterDecision(10, false);
				int LA10_1 = input.LA(1);

				if ((LA10_1==FUNCTION_ARGUMENT))
				{
					alt10 = 1;
				}


				} finally { DebugExitDecision(10); }
				switch (alt10)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:71:25: argument
					{
					DebugLocation(71, 25);
					PushFollow(Follow._argument_in_arguments281);
					argument();
					PopFollow();


					}
					break;

				default:
					if (cnt10 >= 1)
						goto loop10;

					EarlyExitException eee10 = new EarlyExitException( 10, input );
					DebugRecognitionException(eee10);
					throw eee10;
				}
				cnt10++;
			}
			loop10:
				;

			} finally { DebugExitSubRule(10); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("arguments", 9);
			LeaveRule("arguments", 9);
			LeaveRule_arguments();
		}
		DebugLocation(72, 1);
		} finally { DebugExitRule(GrammarFileName, "arguments"); }
		return;

	}
	// $ANTLR end "arguments"

	partial void EnterRule_argument();
	partial void LeaveRule_argument();
	// $ANTLR start "argument"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:74:1: argument : ^( FUNCTION_ARGUMENT value ) ;
	[GrammarRule("argument")]
	private void argument()
	{
		EnterRule_argument();
		EnterRule("argument", 10);
		TraceIn("argument", 10);
		try { DebugEnterRule(GrammarFileName, "argument");
		DebugLocation(74, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:75:2: ( ^( FUNCTION_ARGUMENT value ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:75:4: ^( FUNCTION_ARGUMENT value )
			{
			DebugLocation(75, 4);
			DebugLocation(75, 6);
			Match(input,FUNCTION_ARGUMENT,Follow._FUNCTION_ARGUMENT_in_argument296); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(75, 24);
			PushFollow(Follow._value_in_argument298);
			value();
			PopFollow();


			Match(input, TokenTypes.Up, null); 

			DebugLocation(75, 31);

					

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("argument", 10);
			LeaveRule("argument", 10);
			LeaveRule_argument();
		}
		DebugLocation(77, 1);
		} finally { DebugExitRule(GrammarFileName, "argument"); }
		return;

	}
	// $ANTLR end "argument"

	partial void EnterRule_program();
	partial void LeaveRule_program();
	// $ANTLR start "program"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:81:1: program : ^( PROGRAM ( statement )+ ) ;
	[GrammarRule("program")]
	private void program()
	{
		EnterRule_program();
		EnterRule("program", 11);
		TraceIn("program", 11);
		try { DebugEnterRule(GrammarFileName, "program");
		DebugLocation(81, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:82:2: ( ^( PROGRAM ( statement )+ ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:82:4: ^( PROGRAM ( statement )+ )
			{
			DebugLocation(82, 4);
			DebugLocation(82, 6);
			Match(input,PROGRAM,Follow._PROGRAM_in_program315); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(82, 14);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:82:14: ( statement )+
			int cnt11=0;
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=2;
				try { DebugEnterDecision(11, false);
				int LA11_1 = input.LA(1);

				if ((LA11_1==ASSIGNMENT||LA11_1==DECLARATION||LA11_1==FUNCTION_CALL))
				{
					alt11 = 1;
				}


				} finally { DebugExitDecision(11); }
				switch (alt11)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:82:15: statement
					{
					DebugLocation(82, 15);
					PushFollow(Follow._statement_in_program318);
					statement();
					PopFollow();


					}
					break;

				default:
					if (cnt11 >= 1)
						goto loop11;

					EarlyExitException eee11 = new EarlyExitException( 11, input );
					DebugRecognitionException(eee11);
					throw eee11;
				}
				cnt11++;
			}
			loop11:
				;

			} finally { DebugExitSubRule(11); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("program", 11);
			LeaveRule("program", 11);
			LeaveRule_program();
		}
		DebugLocation(83, 1);
		} finally { DebugExitRule(GrammarFileName, "program"); }
		return;

	}
	// $ANTLR end "program"

	partial void EnterRule_statement();
	partial void LeaveRule_statement();
	// $ANTLR start "statement"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:85:1: statement returns [int retNumDeclarations] : ( declaration | assignment | functionCall );
	[GrammarRule("statement")]
	private int statement()
	{
		EnterRule_statement();
		EnterRule("statement", 12);
		TraceIn("statement", 12);
		int retNumDeclarations = default(int);



			int numDeclarations = 0;

		try { DebugEnterRule(GrammarFileName, "statement");
		DebugLocation(85, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:92:2: ( declaration | assignment | functionCall )
			int alt12=3;
			try { DebugEnterDecision(12, false);
			switch (input.LA(1))
			{
			case DECLARATION:
				{
				alt12 = 1;
				}
				break;
			case ASSIGNMENT:
				{
				alt12 = 2;
				}
				break;
			case FUNCTION_CALL:
				{
				alt12 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 12, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(12); }
			switch (alt12)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:92:4: declaration
				{
				DebugLocation(92, 4);
				PushFollow(Follow._declaration_in_statement346);
				declaration();
				PopFollow();

				DebugLocation(92, 16);
				 numDeclarations++; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:93:4: assignment
				{
				DebugLocation(93, 4);
				PushFollow(Follow._assignment_in_statement353);
				assignment();
				PopFollow();


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:94:4: functionCall
				{
				DebugLocation(94, 4);
				PushFollow(Follow._functionCall_in_statement358);
				functionCall();
				PopFollow();


				}
				break;

			}

				retNumDeclarations = numDeclarations;

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("statement", 12);
			LeaveRule("statement", 12);
			LeaveRule_statement();
		}
		DebugLocation(95, 1);
		} finally { DebugExitRule(GrammarFileName, "statement"); }
		return retNumDeclarations;

	}
	// $ANTLR end "statement"

	partial void EnterRule_declaration();
	partial void LeaveRule_declaration();
	// $ANTLR start "declaration"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:97:1: declaration : ^( DECLARATION ID v= ID ) ;
	[GrammarRule("declaration")]
	private void declaration()
	{
		EnterRule_declaration();
		EnterRule("declaration", 13);
		TraceIn("declaration", 13);
		CommonTree v = default(CommonTree);

		try { DebugEnterRule(GrammarFileName, "declaration");
		DebugLocation(97, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:98:2: ( ^( DECLARATION ID v= ID ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:98:4: ^( DECLARATION ID v= ID )
			{
			DebugLocation(98, 4);
			DebugLocation(98, 6);
			Match(input,DECLARATION,Follow._DECLARATION_in_declaration371); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(98, 18);
			Match(input,ID,Follow._ID_in_declaration373); 
			DebugLocation(98, 22);
			v=(CommonTree)Match(input,ID,Follow._ID_in_declaration377); 

			Match(input, TokenTypes.Up, null); 

			DebugLocation(98, 27);

							

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("declaration", 13);
			LeaveRule("declaration", 13);
			LeaveRule_declaration();
		}
		DebugLocation(100, 1);
		} finally { DebugExitRule(GrammarFileName, "declaration"); }
		return;

	}
	// $ANTLR end "declaration"

	partial void EnterRule_assignment();
	partial void LeaveRule_assignment();
	// $ANTLR start "assignment"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:102:1: assignment : ^( ASSIGNMENT v= ID addSubExp ) ;
	[GrammarRule("assignment")]
	private void assignment()
	{
		EnterRule_assignment();
		EnterRule("assignment", 14);
		TraceIn("assignment", 14);
		CommonTree v = default(CommonTree);

		try { DebugEnterRule(GrammarFileName, "assignment");
		DebugLocation(102, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:103:2: ( ^( ASSIGNMENT v= ID addSubExp ) )
			DebugEnterAlt(1);
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:103:4: ^( ASSIGNMENT v= ID addSubExp )
			{
			DebugLocation(103, 4);
			DebugLocation(103, 6);
			Match(input,ASSIGNMENT,Follow._ASSIGNMENT_in_assignment393); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(103, 18);
			v=(CommonTree)Match(input,ID,Follow._ID_in_assignment397); 
			DebugLocation(103, 22);
			PushFollow(Follow._addSubExp_in_assignment399);
			addSubExp();
			PopFollow();


			Match(input, TokenTypes.Up, null); 

			DebugLocation(103, 33);

							

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("assignment", 14);
			LeaveRule("assignment", 14);
			LeaveRule_assignment();
		}
		DebugLocation(105, 1);
		} finally { DebugExitRule(GrammarFileName, "assignment"); }
		return;

	}
	// $ANTLR end "assignment"

	partial void EnterRule_addSubExp();
	partial void LeaveRule_addSubExp();
	// $ANTLR start "addSubExp"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:107:1: addSubExp : ( mulDivExp | ^( '+' mulDivExp mulDivExp ) | ^( '-' mulDivExp mulDivExp ) );
	[GrammarRule("addSubExp")]
	private void addSubExp()
	{
		EnterRule_addSubExp();
		EnterRule("addSubExp", 15);
		TraceIn("addSubExp", 15);
		try { DebugEnterRule(GrammarFileName, "addSubExp");
		DebugLocation(107, 3);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:108:2: ( mulDivExp | ^( '+' mulDivExp mulDivExp ) | ^( '-' mulDivExp mulDivExp ) )
			int alt13=3;
			try { DebugEnterDecision(13, false);
			switch (input.LA(1))
			{
			case LITERAL:
			case PARENEXP:
			case UNARY:
			case VARIABLE:
			case 30:
			case 34:
				{
				alt13 = 1;
				}
				break;
			case 31:
				{
				alt13 = 2;
				}
				break;
			case 33:
				{
				alt13 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 13, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:108:5: mulDivExp
				{
				DebugLocation(108, 5);
				PushFollow(Follow._mulDivExp_in_addSubExp415);
				mulDivExp();
				PopFollow();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:109:7: ^( '+' mulDivExp mulDivExp )
				{
				DebugLocation(109, 7);
				DebugLocation(109, 9);
				Match(input,31,Follow._31_in_addSubExp424); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(109, 13);
				PushFollow(Follow._mulDivExp_in_addSubExp426);
				mulDivExp();
				PopFollow();

				DebugLocation(109, 23);
				PushFollow(Follow._mulDivExp_in_addSubExp428);
				mulDivExp();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(109, 34);

				  		

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:111:7: ^( '-' mulDivExp mulDivExp )
				{
				DebugLocation(111, 7);
				DebugLocation(111, 9);
				Match(input,33,Follow._33_in_addSubExp440); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(111, 13);
				PushFollow(Follow._mulDivExp_in_addSubExp442);
				mulDivExp();
				PopFollow();

				DebugLocation(111, 23);
				PushFollow(Follow._mulDivExp_in_addSubExp444);
				mulDivExp();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(111, 34);

				  		

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("addSubExp", 15);
			LeaveRule("addSubExp", 15);
			LeaveRule_addSubExp();
		}
		DebugLocation(113, 3);
		} finally { DebugExitRule(GrammarFileName, "addSubExp"); }
		return;

	}
	// $ANTLR end "addSubExp"

	partial void EnterRule_mulDivExp();
	partial void LeaveRule_mulDivExp();
	// $ANTLR start "mulDivExp"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:115:1: mulDivExp : ( unaryExp | ^( '*' unaryExp unaryExp ) | ^( '/' unaryExp unaryExp ) );
	[GrammarRule("mulDivExp")]
	private void mulDivExp()
	{
		EnterRule_mulDivExp();
		EnterRule("mulDivExp", 16);
		TraceIn("mulDivExp", 16);
		try { DebugEnterRule(GrammarFileName, "mulDivExp");
		DebugLocation(115, 3);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:116:2: ( unaryExp | ^( '*' unaryExp unaryExp ) | ^( '/' unaryExp unaryExp ) )
			int alt14=3;
			try { DebugEnterDecision(14, false);
			switch (input.LA(1))
			{
			case LITERAL:
			case PARENEXP:
			case UNARY:
			case VARIABLE:
				{
				alt14 = 1;
				}
				break;
			case 30:
				{
				alt14 = 2;
				}
				break;
			case 34:
				{
				alt14 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 14, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(14); }
			switch (alt14)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:116:5: unaryExp
				{
				DebugLocation(116, 5);
				PushFollow(Follow._unaryExp_in_mulDivExp461);
				unaryExp();
				PopFollow();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:117:7: ^( '*' unaryExp unaryExp )
				{
				DebugLocation(117, 7);
				DebugLocation(117, 9);
				Match(input,30,Follow._30_in_mulDivExp470); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(117, 13);
				PushFollow(Follow._unaryExp_in_mulDivExp472);
				unaryExp();
				PopFollow();

				DebugLocation(117, 22);
				PushFollow(Follow._unaryExp_in_mulDivExp474);
				unaryExp();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(117, 32);

				  		

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:119:6: ^( '/' unaryExp unaryExp )
				{
				DebugLocation(119, 6);
				DebugLocation(119, 8);
				Match(input,34,Follow._34_in_mulDivExp485); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(119, 12);
				PushFollow(Follow._unaryExp_in_mulDivExp487);
				unaryExp();
				PopFollow();

				DebugLocation(119, 21);
				PushFollow(Follow._unaryExp_in_mulDivExp489);
				unaryExp();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(119, 31);

				 		

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("mulDivExp", 16);
			LeaveRule("mulDivExp", 16);
			LeaveRule_mulDivExp();
		}
		DebugLocation(121, 3);
		} finally { DebugExitRule(GrammarFileName, "mulDivExp"); }
		return;

	}
	// $ANTLR end "mulDivExp"

	partial void EnterRule_unaryExp();
	partial void LeaveRule_unaryExp();
	// $ANTLR start "unaryExp"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:123:1: unaryExp : ( ^( UNARY value ) | value );
	[GrammarRule("unaryExp")]
	private void unaryExp()
	{
		EnterRule_unaryExp();
		EnterRule("unaryExp", 17);
		TraceIn("unaryExp", 17);
		try { DebugEnterRule(GrammarFileName, "unaryExp");
		DebugLocation(123, 3);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:124:4: ( ^( UNARY value ) | value )
			int alt15=2;
			try { DebugEnterDecision(15, false);
			int LA15_1 = input.LA(1);

			if ((LA15_1==UNARY))
			{
				alt15 = 1;
			}
			else if ((LA15_1==LITERAL||LA15_1==PARENEXP||LA15_1==VARIABLE))
			{
				alt15 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 15, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:124:7: ^( UNARY value )
				{
				DebugLocation(124, 7);
				DebugLocation(124, 9);
				Match(input,UNARY,Follow._UNARY_in_unaryExp510); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(124, 15);
				PushFollow(Follow._value_in_unaryExp512);
				value();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(124, 22);

				  			

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:126:5: value
				{
				DebugLocation(126, 5);
				PushFollow(Follow._value_in_unaryExp521);
				value();
				PopFollow();


				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("unaryExp", 17);
			LeaveRule("unaryExp", 17);
			LeaveRule_unaryExp();
		}
		DebugLocation(127, 3);
		} finally { DebugExitRule(GrammarFileName, "unaryExp"); }
		return;

	}
	// $ANTLR end "unaryExp"

	partial void EnterRule_value();
	partial void LeaveRule_value();
	// $ANTLR start "value"
	// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:129:1: value : ( ^( VARIABLE ID ) | ^( LITERAL TYPE_INT INT ) | ^( LITERAL TYPE_FLOAT FLOAT ) | ^( PARENEXP addSubExp ) );
	[GrammarRule("value")]
	private void value()
	{
		EnterRule_value();
		EnterRule("value", 18);
		TraceIn("value", 18);
		try { DebugEnterRule(GrammarFileName, "value");
		DebugLocation(129, 1);
		try
		{
			// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:130:2: ( ^( VARIABLE ID ) | ^( LITERAL TYPE_INT INT ) | ^( LITERAL TYPE_FLOAT FLOAT ) | ^( PARENEXP addSubExp ) )
			int alt16=4;
			try { DebugEnterDecision(16, false);
			switch (input.LA(1))
			{
			case VARIABLE:
				{
				alt16 = 1;
				}
				break;
			case LITERAL:
				{
				int LA16_2 = input.LA(2);

				if ((LA16_2==DOWN))
				{
					int LA16_3 = input.LA(3);

					if ((LA16_3==TYPE_INT))
					{
						alt16 = 2;
					}
					else if ((LA16_3==TYPE_FLOAT))
					{
						alt16 = 3;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 16, 4, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 16, 2, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case PARENEXP:
				{
				alt16 = 4;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 16, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(16); }
			switch (alt16)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:130:4: ^( VARIABLE ID )
				{
				DebugLocation(130, 4);
				DebugLocation(130, 6);
				Match(input,VARIABLE,Follow._VARIABLE_in_value538); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(130, 15);
				Match(input,ID,Follow._ID_in_value540); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(130, 19);


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:131:4: ^( LITERAL TYPE_INT INT )
				{
				DebugLocation(131, 4);
				DebugLocation(131, 6);
				Match(input,LITERAL,Follow._LITERAL_in_value549); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(131, 14);
				Match(input,TYPE_INT,Follow._TYPE_INT_in_value551); 
				DebugLocation(131, 23);
				Match(input,INT,Follow._INT_in_value553); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(131, 28);

									

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:133:4: ^( LITERAL TYPE_FLOAT FLOAT )
				{
				DebugLocation(133, 4);
				DebugLocation(133, 6);
				Match(input,LITERAL,Follow._LITERAL_in_value562); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(133, 14);
				Match(input,TYPE_FLOAT,Follow._TYPE_FLOAT_in_value564); 
				DebugLocation(133, 25);
				Match(input,FLOAT,Follow._FLOAT_in_value566); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(133, 32);
				 
									

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\Repos\\NeoInterpreter\\NeoCompiler\\NeoTreePass1.g:135:4: ^( PARENEXP addSubExp )
				{
				DebugLocation(135, 4);
				DebugLocation(135, 6);
				Match(input,PARENEXP,Follow._PARENEXP_in_value575); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(135, 15);
				PushFollow(Follow._addSubExp_in_value577);
				addSubExp();
				PopFollow();


				Match(input, TokenTypes.Up, null); 


				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("value", 18);
			LeaveRule("value", 18);
			LeaveRule_value();
		}
		DebugLocation(136, 1);
		} finally { DebugExitRule(GrammarFileName, "value"); }
		return;

	}
	// $ANTLR end "value"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _FILE_in_file54 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _script_in_file56 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _SCRIPT_in_script70 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _functionDefs_in_script72 = new BitSet(new ulong[]{0x0000000000200008UL});
		public static readonly BitSet _program_in_script75 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _SCRIPT_in_script86 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _program_in_script88 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _FUNCTION_DEFS_in_functionDefs104 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _functionDef_in_functionDefs106 = new BitSet(new ulong[]{0x0000000000002008UL});
		public static readonly BitSet _FUNCTION_DEF_in_functionDef126 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_functionDef130 = new BitSet(new ulong[]{0x0000000000080808UL});
		public static readonly BitSet _parameters_in_functionDef135 = new BitSet(new ulong[]{0x0000000000000808UL});
		public static readonly BitSet _body_in_functionDef144 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _FUNCTION_BODY_in_body172 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _statement_in_body177 = new BitSet(new ulong[]{0x0000000000001058UL});
		public static readonly BitSet _PARAMS_in_parameters210 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _param_in_parameters213 = new BitSet(new ulong[]{0x0000000000040008UL});
		public static readonly BitSet _PARAM_in_param231 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_param233 = new BitSet(new ulong[]{0x0000000000008000UL});
		public static readonly BitSet _ID_in_param235 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _FUNCTION_CALL_in_functionCall254 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_functionCall258 = new BitSet(new ulong[]{0x0000000000000408UL});
		public static readonly BitSet _arguments_in_functionCall262 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _FUNCTION_ARGUMENTS_in_arguments279 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _argument_in_arguments281 = new BitSet(new ulong[]{0x0000000000000208UL});
		public static readonly BitSet _FUNCTION_ARGUMENT_in_argument296 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _value_in_argument298 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _PROGRAM_in_program315 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _statement_in_program318 = new BitSet(new ulong[]{0x0000000000001058UL});
		public static readonly BitSet _declaration_in_statement346 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _assignment_in_statement353 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _functionCall_in_statement358 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _DECLARATION_in_declaration371 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_declaration373 = new BitSet(new ulong[]{0x0000000000008000UL});
		public static readonly BitSet _ID_in_declaration377 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _ASSIGNMENT_in_assignment393 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_assignment397 = new BitSet(new ulong[]{0x00000006C6120000UL});
		public static readonly BitSet _addSubExp_in_assignment399 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _mulDivExp_in_addSubExp415 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _31_in_addSubExp424 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _mulDivExp_in_addSubExp426 = new BitSet(new ulong[]{0x0000000446120000UL});
		public static readonly BitSet _mulDivExp_in_addSubExp428 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _33_in_addSubExp440 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _mulDivExp_in_addSubExp442 = new BitSet(new ulong[]{0x0000000446120000UL});
		public static readonly BitSet _mulDivExp_in_addSubExp444 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _unaryExp_in_mulDivExp461 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _30_in_mulDivExp470 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _unaryExp_in_mulDivExp472 = new BitSet(new ulong[]{0x0000000006120000UL});
		public static readonly BitSet _unaryExp_in_mulDivExp474 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _34_in_mulDivExp485 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _unaryExp_in_mulDivExp487 = new BitSet(new ulong[]{0x0000000006120000UL});
		public static readonly BitSet _unaryExp_in_mulDivExp489 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _UNARY_in_unaryExp510 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _value_in_unaryExp512 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _value_in_unaryExp521 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _VARIABLE_in_value538 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_value540 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _LITERAL_in_value549 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _TYPE_INT_in_value551 = new BitSet(new ulong[]{0x0000010000000000UL});
		public static readonly BitSet _INT_in_value553 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _LITERAL_in_value562 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _TYPE_FLOAT_in_value564 = new BitSet(new ulong[]{0x0000008000000000UL});
		public static readonly BitSet _FLOAT_in_value566 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _PARENEXP_in_value575 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _addSubExp_in_value577 = new BitSet(new ulong[]{0x0000000000000008UL});
	}
	#endregion Follow sets
}
