//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5 C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g 2014-06-18 14:16:25

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using Neo;
using System;


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5")]
[System.CLSCompliant(false)]
public partial class NeoTreePass2 : Antlr.Runtime.Tree.TreeParser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "ASSIGNMENT", "COMMENT", "DECLARATION", "FILE", "FLOAT_VALUE", "FUNCTION_ARGUMENT", "FUNCTION_ARGUMENTS", "FUNCTION_BODY", "FUNCTION_CALL", "FUNCTION_DEF", "FUNCTION_DEFS", "ID", "INT_VALUE", "LITERAL", "PARAM", "PARAMS", "PARENEXP", "PROGRAM", "SCRIPT", "TYPE_FLOAT", "TYPE_INT", "UNARY", "VARIABLE", "WS", "'('", "')'", "'*'", "'+'", "','", "'-'", "'/'", "';'", "'='", "'{'", "'}'", "FLOAT", "INT"
	};
	public const int EOF=-1;
	public const int T__28=28;
	public const int T__29=29;
	public const int T__30=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int T__33=33;
	public const int T__34=34;
	public const int T__35=35;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int ASSIGNMENT=4;
	public const int COMMENT=5;
	public const int DECLARATION=6;
	public const int FILE=7;
	public const int FLOAT_VALUE=8;
	public const int FUNCTION_ARGUMENT=9;
	public const int FUNCTION_ARGUMENTS=10;
	public const int FUNCTION_BODY=11;
	public const int FUNCTION_CALL=12;
	public const int FUNCTION_DEF=13;
	public const int FUNCTION_DEFS=14;
	public const int ID=15;
	public const int INT_VALUE=16;
	public const int LITERAL=17;
	public const int PARAM=18;
	public const int PARAMS=19;
	public const int PARENEXP=20;
	public const int PROGRAM=21;
	public const int SCRIPT=22;
	public const int TYPE_FLOAT=23;
	public const int TYPE_INT=24;
	public const int UNARY=25;
	public const int VARIABLE=26;
	public const int WS=27;
	public const int FLOAT=39;
	public const int INT=40;

	public NeoTreePass2(ITreeNodeStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public NeoTreePass2(ITreeNodeStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}

	public override string[] TokenNames { get { return NeoTreePass2.tokenNames; } }
	public override string GrammarFileName { get { return "C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g"; } }


	public void	Process() {
			file();
		}


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_file();
	partial void LeaveRule_file();
	// $ANTLR start "file"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:21:1: file : (| ^( FILE script ) );
	[GrammarRule("file")]
	private void file()
	{
		EnterRule_file();
		EnterRule("file", 1);
		TraceIn("file", 1);
		try { DebugEnterRule(GrammarFileName, "file");
		DebugLocation(21, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:21:6: (| ^( FILE script ) )
			int alt1=2;
			try { DebugEnterDecision(1, false);
			int LA1_1 = input.LA(1);

			if ((LA1_1==EOF))
			{
				alt1 = 1;
			}
			else if ((LA1_1==FILE))
			{
				alt1 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 1, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:22:2: 
				{
				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:22:4: ^( FILE script )
				{
				DebugLocation(22, 4);
				DebugLocation(22, 6);
				Match(input,FILE,Follow._FILE_in_file54); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(22, 11);
				PushFollow(Follow._script_in_file56);
				script();
				PopFollow();


				Match(input, TokenTypes.Up, null); 


				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("file", 1);
			LeaveRule("file", 1);
			LeaveRule_file();
		}
		DebugLocation(23, 1);
		} finally { DebugExitRule(GrammarFileName, "file"); }
		return;

	}
	// $ANTLR end "file"

	partial void EnterRule_script();
	partial void LeaveRule_script();
	// $ANTLR start "script"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:25:1: script : ( ^( SCRIPT functionDefs ( program )? ) | ^( SCRIPT program ) );
	[GrammarRule("script")]
	private void script()
	{
		EnterRule_script();
		EnterRule("script", 2);
		TraceIn("script", 2);
		try { DebugEnterRule(GrammarFileName, "script");
		DebugLocation(25, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:25:9: ( ^( SCRIPT functionDefs ( program )? ) | ^( SCRIPT program ) )
			int alt3=2;
			try { DebugEnterDecision(3, false);
			int LA3_1 = input.LA(1);

			if ((LA3_1==SCRIPT))
			{
				int LA3_2 = input.LA(2);

				if ((LA3_2==DOWN))
				{
					int LA3_3 = input.LA(3);

					if ((LA3_3==FUNCTION_DEFS))
					{
						alt3 = 1;
					}
					else if ((LA3_3==PROGRAM))
					{
						alt3 = 2;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 3, 2, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 3, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 3, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:25:11: ^( SCRIPT functionDefs ( program )? )
				{
				DebugLocation(25, 11);
				DebugLocation(25, 13);
				Match(input,SCRIPT,Follow._SCRIPT_in_script70); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(25, 20);
				PushFollow(Follow._functionDefs_in_script72);
				functionDefs();
				PopFollow();

				DebugLocation(25, 33);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:25:33: ( program )?
				int alt2=2;
				try { DebugEnterSubRule(2);
				try { DebugEnterDecision(2, false);
				int LA2_1 = input.LA(1);

				if ((LA2_1==PROGRAM))
				{
					alt2 = 1;
				}
				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:25:34: program
					{
					DebugLocation(25, 34);
					PushFollow(Follow._program_in_script75);
					program();
					PopFollow();


					}
					break;

				}
				} finally { DebugExitSubRule(2); }


				Match(input, TokenTypes.Up, null); 

				DebugLocation(25, 45);


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:26:4: ^( SCRIPT program )
				{
				DebugLocation(26, 4);
				DebugLocation(26, 6);
				Match(input,SCRIPT,Follow._SCRIPT_in_script86); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(26, 13);
				PushFollow(Follow._program_in_script88);
				program();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(26, 22);


				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("script", 2);
			LeaveRule("script", 2);
			LeaveRule_script();
		}
		DebugLocation(27, 1);
		} finally { DebugExitRule(GrammarFileName, "script"); }
		return;

	}
	// $ANTLR end "script"

	partial void EnterRule_functionDefs();
	partial void LeaveRule_functionDefs();
	// $ANTLR start "functionDefs"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:29:1: functionDefs : ^( FUNCTION_DEFS ( functionDef )+ ) ;
	[GrammarRule("functionDefs")]
	private void functionDefs()
	{
		EnterRule_functionDefs();
		EnterRule("functionDefs", 3);
		TraceIn("functionDefs", 3);
		try { DebugEnterRule(GrammarFileName, "functionDefs");
		DebugLocation(29, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:30:2: ( ^( FUNCTION_DEFS ( functionDef )+ ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:30:4: ^( FUNCTION_DEFS ( functionDef )+ )
			{
			DebugLocation(30, 4);
			DebugLocation(30, 6);
			Match(input,FUNCTION_DEFS,Follow._FUNCTION_DEFS_in_functionDefs104); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(30, 20);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:30:20: ( functionDef )+
			int cnt4=0;
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, false);
				int LA4_1 = input.LA(1);

				if ((LA4_1==FUNCTION_DEF))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:30:20: functionDef
					{
					DebugLocation(30, 20);
					PushFollow(Follow._functionDef_in_functionDefs106);
					functionDef();
					PopFollow();


					}
					break;

				default:
					if (cnt4 >= 1)
						goto loop4;

					EarlyExitException eee4 = new EarlyExitException( 4, input );
					DebugRecognitionException(eee4);
					throw eee4;
				}
				cnt4++;
			}
			loop4:
				;

			} finally { DebugExitSubRule(4); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("functionDefs", 3);
			LeaveRule("functionDefs", 3);
			LeaveRule_functionDefs();
		}
		DebugLocation(31, 1);
		} finally { DebugExitRule(GrammarFileName, "functionDefs"); }
		return;

	}
	// $ANTLR end "functionDefs"

	partial void EnterRule_functionDef();
	partial void LeaveRule_functionDef();
	// $ANTLR start "functionDef"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:33:1: functionDef : ^( FUNCTION_DEF f= ID ( parameters[funcDef, memory] )? ( body[funcDef, memory] )? ) ;
	[GrammarRule("functionDef")]
	private void functionDef()
	{
		EnterRule_functionDef();
		EnterRule("functionDef", 4);
		TraceIn("functionDef", 4);
		CommonTree f = default(CommonTree);


			FunctionDef funcDef;
			IMemoryDecorator memory = new MemoryDecorator_StackInterface();

		try { DebugEnterRule(GrammarFileName, "functionDef");
		DebugLocation(33, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:41:2: ( ^( FUNCTION_DEF f= ID ( parameters[funcDef, memory] )? ( body[funcDef, memory] )? ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:41:4: ^( FUNCTION_DEF f= ID ( parameters[funcDef, memory] )? ( body[funcDef, memory] )? )
			{
			DebugLocation(41, 4);
			DebugLocation(41, 6);
			Match(input,FUNCTION_DEF,Follow._FUNCTION_DEF_in_functionDef131); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(41, 20);
			f=(CommonTree)Match(input,ID,Follow._ID_in_functionDef135); 
			DebugLocation(41, 24);
			funcDef = ProgramDef.Instance.FunctionDefs[(f!=null?f.Text:default(string))];
			DebugLocation(41, 79);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:41:79: ( parameters[funcDef, memory] )?
			int alt5=2;
			try { DebugEnterSubRule(5);
			try { DebugEnterDecision(5, false);
			int LA5_1 = input.LA(1);

			if ((LA5_1==PARAMS))
			{
				alt5 = 1;
			}
			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:41:80: parameters[funcDef, memory]
				{
				DebugLocation(41, 80);
				PushFollow(Follow._parameters_in_functionDef140);
				parameters(funcDef, memory);
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(5); }

			DebugLocation(41, 110);
			funcDef.PreBodyParse();
			DebugLocation(41, 136);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:41:136: ( body[funcDef, memory] )?
			int alt6=2;
			try { DebugEnterSubRule(6);
			try { DebugEnterDecision(6, false);
			int LA6_1 = input.LA(1);

			if ((LA6_1==FUNCTION_BODY))
			{
				alt6 = 1;
			}
			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:41:137: body[funcDef, memory]
				{
				DebugLocation(41, 137);
				PushFollow(Follow._body_in_functionDef148);
				body(funcDef, memory);
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(6); }


			Match(input, TokenTypes.Up, null); 


			}


				funcDef.PostBodyParse();

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("functionDef", 4);
			LeaveRule("functionDef", 4);
			LeaveRule_functionDef();
		}
		DebugLocation(42, 1);
		} finally { DebugExitRule(GrammarFileName, "functionDef"); }
		return;

	}
	// $ANTLR end "functionDef"

	partial void EnterRule_body();
	partial void LeaveRule_body();
	// $ANTLR start "body"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:44:1: body[FunctionDef funcDef, IMemoryDecorator memory] : ^( FUNCTION_BODY ( statement[memory, funcDef.InstructionStream] )+ ) ;
	[GrammarRule("body")]
	private void body(FunctionDef funcDef, IMemoryDecorator memory)
	{
		EnterRule_body();
		EnterRule("body", 5);
		TraceIn("body", 5);
		try { DebugEnterRule(GrammarFileName, "body");
		DebugLocation(44, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:45:2: ( ^( FUNCTION_BODY ( statement[memory, funcDef.InstructionStream] )+ ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:45:4: ^( FUNCTION_BODY ( statement[memory, funcDef.InstructionStream] )+ )
			{
			DebugLocation(45, 4);
			DebugLocation(45, 6);
			Match(input,FUNCTION_BODY,Follow._FUNCTION_BODY_in_body166); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(45, 20);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:45:20: ( statement[memory, funcDef.InstructionStream] )+
			int cnt7=0;
			try { DebugEnterSubRule(7);
			while (true)
			{
				int alt7=2;
				try { DebugEnterDecision(7, false);
				int LA7_1 = input.LA(1);

				if ((LA7_1==ASSIGNMENT||LA7_1==DECLARATION||LA7_1==FUNCTION_CALL))
				{
					alt7 = 1;
				}


				} finally { DebugExitDecision(7); }
				switch (alt7)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:45:21: statement[memory, funcDef.InstructionStream]
					{
					DebugLocation(45, 21);
					PushFollow(Follow._statement_in_body169);
					statement(memory, funcDef.InstructionStream);
					PopFollow();


					}
					break;

				default:
					if (cnt7 >= 1)
						goto loop7;

					EarlyExitException eee7 = new EarlyExitException( 7, input );
					DebugRecognitionException(eee7);
					throw eee7;
				}
				cnt7++;
			}
			loop7:
				;

			} finally { DebugExitSubRule(7); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("body", 5);
			LeaveRule("body", 5);
			LeaveRule_body();
		}
		DebugLocation(46, 1);
		} finally { DebugExitRule(GrammarFileName, "body"); }
		return;

	}
	// $ANTLR end "body"

	partial void EnterRule_parameters();
	partial void LeaveRule_parameters();
	// $ANTLR start "parameters"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:48:1: parameters[FunctionDef funcDef, IMemoryDecorator memory] : ^( PARAMS ( param[funcDef, memory] )+ ) ;
	[GrammarRule("parameters")]
	private void parameters(FunctionDef funcDef, IMemoryDecorator memory)
	{
		EnterRule_parameters();
		EnterRule("parameters", 6);
		TraceIn("parameters", 6);
		try { DebugEnterRule(GrammarFileName, "parameters");
		DebugLocation(48, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:49:2: ( ^( PARAMS ( param[funcDef, memory] )+ ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:49:4: ^( PARAMS ( param[funcDef, memory] )+ )
			{
			DebugLocation(49, 4);
			DebugLocation(49, 6);
			Match(input,PARAMS,Follow._PARAMS_in_parameters188); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(49, 13);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:49:13: ( param[funcDef, memory] )+
			int cnt8=0;
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_1 = input.LA(1);

				if ((LA8_1==PARAM))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch (alt8)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:49:14: param[funcDef, memory]
					{
					DebugLocation(49, 14);
					PushFollow(Follow._param_in_parameters191);
					param(funcDef, memory);
					PopFollow();


					}
					break;

				default:
					if (cnt8 >= 1)
						goto loop8;

					EarlyExitException eee8 = new EarlyExitException( 8, input );
					DebugRecognitionException(eee8);
					throw eee8;
				}
				cnt8++;
			}
			loop8:
				;

			} finally { DebugExitSubRule(8); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("parameters", 6);
			LeaveRule("parameters", 6);
			LeaveRule_parameters();
		}
		DebugLocation(50, 1);
		} finally { DebugExitRule(GrammarFileName, "parameters"); }
		return;

	}
	// $ANTLR end "parameters"

	partial void EnterRule_param();
	partial void LeaveRule_param();
	// $ANTLR start "param"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:52:1: param[FunctionDef funcDef, IMemoryDecorator memory] : ( ^( PARAM TYPE_INT v= ID ) | ^( PARAM TYPE_FLOAT v= ID ) );
	[GrammarRule("param")]
	private void param(FunctionDef funcDef, IMemoryDecorator memory)
	{
		EnterRule_param();
		EnterRule("param", 7);
		TraceIn("param", 7);
		CommonTree v = default(CommonTree);

		try { DebugEnterRule(GrammarFileName, "param");
		DebugLocation(52, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:53:2: ( ^( PARAM TYPE_INT v= ID ) | ^( PARAM TYPE_FLOAT v= ID ) )
			int alt9=2;
			try { DebugEnterDecision(9, false);
			int LA9_1 = input.LA(1);

			if ((LA9_1==PARAM))
			{
				int LA9_2 = input.LA(2);

				if ((LA9_2==DOWN))
				{
					int LA9_3 = input.LA(3);

					if ((LA9_3==TYPE_INT))
					{
						alt9 = 1;
					}
					else if ((LA9_3==TYPE_FLOAT))
					{
						alt9 = 2;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 9, 2, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 9, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 9, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:53:4: ^( PARAM TYPE_INT v= ID )
				{
				DebugLocation(53, 4);
				DebugLocation(53, 6);
				Match(input,PARAM,Follow._PARAM_in_param210); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(53, 12);
				Match(input,TYPE_INT,Follow._TYPE_INT_in_param212); 
				DebugLocation(53, 22);
				v=(CommonTree)Match(input,ID,Follow._ID_in_param216); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(53, 27);

						memory.AllocateStorage( (v!=null?v.Text:default(string)), typeof(int), funcDef );
					

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:56:4: ^( PARAM TYPE_FLOAT v= ID )
				{
				DebugLocation(56, 4);
				DebugLocation(56, 6);
				Match(input,PARAM,Follow._PARAM_in_param225); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(56, 12);
				Match(input,TYPE_FLOAT,Follow._TYPE_FLOAT_in_param227); 
				DebugLocation(56, 24);
				v=(CommonTree)Match(input,ID,Follow._ID_in_param231); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(56, 29);

						memory.AllocateStorage( (v!=null?v.Text:default(string)), typeof(float), funcDef );
					

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("param", 7);
			LeaveRule("param", 7);
			LeaveRule_param();
		}
		DebugLocation(59, 1);
		} finally { DebugExitRule(GrammarFileName, "param"); }
		return;

	}
	// $ANTLR end "param"

	partial void EnterRule_functionCall();
	partial void LeaveRule_functionCall();
	// $ANTLR start "functionCall"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:63:1: functionCall[List<Instruction> instructionStream] : ^( FUNCTION_CALL f= ID ( arguments[instructionStream] )? ) ;
	[GrammarRule("functionCall")]
	private void functionCall(List<Instruction> instructionStream)
	{
		EnterRule_functionCall();
		EnterRule("functionCall", 8);
		TraceIn("functionCall", 8);
		CommonTree f = default(CommonTree);


			FunctionDef funcDef;

		try { DebugEnterRule(GrammarFileName, "functionCall");
		DebugLocation(63, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:67:2: ( ^( FUNCTION_CALL f= ID ( arguments[instructionStream] )? ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:67:4: ^( FUNCTION_CALL f= ID ( arguments[instructionStream] )? )
			{
			DebugLocation(67, 4);
			DebugLocation(67, 6);
			Match(input,FUNCTION_CALL,Follow._FUNCTION_CALL_in_functionCall256); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(67, 21);
			f=(CommonTree)Match(input,ID,Follow._ID_in_functionCall260); 
			DebugLocation(67, 25);

							funcDef = ProgramDef.Instance.FunctionDefs[(f!=null?f.Text:default(string))];
							instructionStream.Add( new PushFrameInstruction(new LiteralValue(funcDef.StackFrameSize)) );
						
			DebugLocation(70, 6);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:70:6: ( arguments[instructionStream] )?
			int alt10=2;
			try { DebugEnterSubRule(10);
			try { DebugEnterDecision(10, false);
			int LA10_1 = input.LA(1);

			if ((LA10_1==FUNCTION_ARGUMENTS))
			{
				alt10 = 1;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:70:6: arguments[instructionStream]
				{
				DebugLocation(70, 6);
				PushFollow(Follow._arguments_in_functionCall264);
				arguments(instructionStream);
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(10); }


			Match(input, TokenTypes.Up, null); 

			DebugLocation(70, 37);

						Value retAddr = new LiteralValue(instructionStream.Count + 2);
						instructionStream.Add( new PushInstruction(retAddr) );
						instructionStream.Add( new CallInstruction(new LiteralValue(funcDef.StartAddress)) );
						instructionStream.Add( new PopFrameInstruction() );
					

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("functionCall", 8);
			LeaveRule("functionCall", 8);
			LeaveRule_functionCall();
		}
		DebugLocation(76, 1);
		} finally { DebugExitRule(GrammarFileName, "functionCall"); }
		return;

	}
	// $ANTLR end "functionCall"

	partial void EnterRule_arguments();
	partial void LeaveRule_arguments();
	// $ANTLR start "arguments"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:78:1: arguments[List<Instruction> instructionStream] : ^( FUNCTION_ARGUMENTS ( argument[instructionStream] )+ ) ;
	[GrammarRule("arguments")]
	private void arguments(List<Instruction> instructionStream)
	{
		EnterRule_arguments();
		EnterRule("arguments", 9);
		TraceIn("arguments", 9);
		try { DebugEnterRule(GrammarFileName, "arguments");
		DebugLocation(78, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:79:2: ( ^( FUNCTION_ARGUMENTS ( argument[instructionStream] )+ ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:79:4: ^( FUNCTION_ARGUMENTS ( argument[instructionStream] )+ )
			{
			DebugLocation(79, 4);
			DebugLocation(79, 6);
			Match(input,FUNCTION_ARGUMENTS,Follow._FUNCTION_ARGUMENTS_in_arguments284); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(79, 25);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:79:25: ( argument[instructionStream] )+
			int cnt11=0;
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=2;
				try { DebugEnterDecision(11, false);
				int LA11_1 = input.LA(1);

				if ((LA11_1==FUNCTION_ARGUMENT))
				{
					alt11 = 1;
				}


				} finally { DebugExitDecision(11); }
				switch (alt11)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:79:26: argument[instructionStream]
					{
					DebugLocation(79, 26);
					PushFollow(Follow._argument_in_arguments287);
					argument(instructionStream);
					PopFollow();


					}
					break;

				default:
					if (cnt11 >= 1)
						goto loop11;

					EarlyExitException eee11 = new EarlyExitException( 11, input );
					DebugRecognitionException(eee11);
					throw eee11;
				}
				cnt11++;
			}
			loop11:
				;

			} finally { DebugExitSubRule(11); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("arguments", 9);
			LeaveRule("arguments", 9);
			LeaveRule_arguments();
		}
		DebugLocation(80, 1);
		} finally { DebugExitRule(GrammarFileName, "arguments"); }
		return;

	}
	// $ANTLR end "arguments"

	partial void EnterRule_argument();
	partial void LeaveRule_argument();
	// $ANTLR start "argument"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:82:1: argument[List<Instruction> instructionStream] : ^( FUNCTION_ARGUMENT v= value[instructionStream] ) ;
	[GrammarRule("argument")]
	private void argument(List<Instruction> instructionStream)
	{
		EnterRule_argument();
		EnterRule("argument", 10);
		TraceIn("argument", 10);
		Value v = default(Value);

		try { DebugEnterRule(GrammarFileName, "argument");
		DebugLocation(82, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:83:2: ( ^( FUNCTION_ARGUMENT v= value[instructionStream] ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:83:4: ^( FUNCTION_ARGUMENT v= value[instructionStream] )
			{
			DebugLocation(83, 4);
			DebugLocation(83, 6);
			Match(input,FUNCTION_ARGUMENT,Follow._FUNCTION_ARGUMENT_in_argument306); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(83, 25);
			PushFollow(Follow._value_in_argument310);
			v=value(instructionStream);
			PopFollow();


			Match(input, TokenTypes.Up, null); 

			DebugLocation(83, 52);

					instructionStream.Add( new PushInstruction(v) );
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("argument", 10);
			LeaveRule("argument", 10);
			LeaveRule_argument();
		}
		DebugLocation(86, 1);
		} finally { DebugExitRule(GrammarFileName, "argument"); }
		return;

	}
	// $ANTLR end "argument"

	partial void EnterRule_program();
	partial void LeaveRule_program();
	// $ANTLR start "program"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:90:1: program : ^( PROGRAM ( statement[memory, CPU.Instance.InstructionStream] )+ ) ;
	[GrammarRule("program")]
	private void program()
	{
		EnterRule_program();
		EnterRule("program", 11);
		TraceIn("program", 11);

			IMemoryDecorator memory = new MemoryDecorator_HeapInterface();

		try { DebugEnterRule(GrammarFileName, "program");
		DebugLocation(90, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:94:2: ( ^( PROGRAM ( statement[memory, CPU.Instance.InstructionStream] )+ ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:94:4: ^( PROGRAM ( statement[memory, CPU.Instance.InstructionStream] )+ )
			{
			DebugLocation(94, 4);
			DebugLocation(94, 6);
			Match(input,PROGRAM,Follow._PROGRAM_in_program333); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(94, 14);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:94:14: ( statement[memory, CPU.Instance.InstructionStream] )+
			int cnt12=0;
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=2;
				try { DebugEnterDecision(12, false);
				int LA12_1 = input.LA(1);

				if ((LA12_1==ASSIGNMENT||LA12_1==DECLARATION||LA12_1==FUNCTION_CALL))
				{
					alt12 = 1;
				}


				} finally { DebugExitDecision(12); }
				switch (alt12)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:94:15: statement[memory, CPU.Instance.InstructionStream]
					{
					DebugLocation(94, 15);
					PushFollow(Follow._statement_in_program336);
					statement(memory, CPU.Instance.InstructionStream);
					PopFollow();


					}
					break;

				default:
					if (cnt12 >= 1)
						goto loop12;

					EarlyExitException eee12 = new EarlyExitException( 12, input );
					DebugRecognitionException(eee12);
					throw eee12;
				}
				cnt12++;
			}
			loop12:
				;

			} finally { DebugExitSubRule(12); }


			Match(input, TokenTypes.Up, null); 

			DebugLocation(94, 68);

					CPU.Instance.InstructionStream.Add( new EndofProgramInstruction() );
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("program", 11);
			LeaveRule("program", 11);
			LeaveRule_program();
		}
		DebugLocation(97, 1);
		} finally { DebugExitRule(GrammarFileName, "program"); }
		return;

	}
	// $ANTLR end "program"

	partial void EnterRule_statement();
	partial void LeaveRule_statement();
	// $ANTLR start "statement"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:99:1: statement[IMemoryDecorator memory, List<Instruction> instructionStream] : ( declaration[memory] | assignment[instructionStream] | functionCall[instructionStream] );
	[GrammarRule("statement")]
	private void statement(IMemoryDecorator memory, List<Instruction> instructionStream)
	{
		EnterRule_statement();
		EnterRule("statement", 12);
		TraceIn("statement", 12);
		try { DebugEnterRule(GrammarFileName, "statement");
		DebugLocation(99, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:100:2: ( declaration[memory] | assignment[instructionStream] | functionCall[instructionStream] )
			int alt13=3;
			try { DebugEnterDecision(13, false);
			switch (input.LA(1))
			{
			case DECLARATION:
				{
				alt13 = 1;
				}
				break;
			case ASSIGNMENT:
				{
				alt13 = 2;
				}
				break;
			case FUNCTION_CALL:
				{
				alt13 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 13, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:100:4: declaration[memory]
				{
				DebugLocation(100, 4);
				PushFollow(Follow._declaration_in_statement356);
				declaration(memory);
				PopFollow();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:101:4: assignment[instructionStream]
				{
				DebugLocation(101, 4);
				PushFollow(Follow._assignment_in_statement362);
				assignment(instructionStream);
				PopFollow();


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:102:4: functionCall[instructionStream]
				{
				DebugLocation(102, 4);
				PushFollow(Follow._functionCall_in_statement368);
				functionCall(instructionStream);
				PopFollow();


				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("statement", 12);
			LeaveRule("statement", 12);
			LeaveRule_statement();
		}
		DebugLocation(103, 1);
		} finally { DebugExitRule(GrammarFileName, "statement"); }
		return;

	}
	// $ANTLR end "statement"

	partial void EnterRule_declaration();
	partial void LeaveRule_declaration();
	// $ANTLR start "declaration"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:105:1: declaration[IMemoryDecorator memory] : ( ^( DECLARATION TYPE_INT v= ID ) | ^( DECLARATION TYPE_FLOAT v= ID ) );
	[GrammarRule("declaration")]
	private void declaration(IMemoryDecorator memory)
	{
		EnterRule_declaration();
		EnterRule("declaration", 13);
		TraceIn("declaration", 13);
		CommonTree v = default(CommonTree);

		try { DebugEnterRule(GrammarFileName, "declaration");
		DebugLocation(105, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:106:2: ( ^( DECLARATION TYPE_INT v= ID ) | ^( DECLARATION TYPE_FLOAT v= ID ) )
			int alt14=2;
			try { DebugEnterDecision(14, false);
			int LA14_1 = input.LA(1);

			if ((LA14_1==DECLARATION))
			{
				int LA14_2 = input.LA(2);

				if ((LA14_2==DOWN))
				{
					int LA14_3 = input.LA(3);

					if ((LA14_3==TYPE_INT))
					{
						alt14 = 1;
					}
					else if ((LA14_3==TYPE_FLOAT))
					{
						alt14 = 2;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 14, 2, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 14, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 14, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(14); }
			switch (alt14)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:106:4: ^( DECLARATION TYPE_INT v= ID )
				{
				DebugLocation(106, 4);
				DebugLocation(106, 6);
				Match(input,DECLARATION,Follow._DECLARATION_in_declaration383); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(106, 18);
				Match(input,TYPE_INT,Follow._TYPE_INT_in_declaration385); 
				DebugLocation(106, 28);
				v=(CommonTree)Match(input,ID,Follow._ID_in_declaration389); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(106, 33);

						memory.AllocateStorage( (v!=null?v.Text:default(string)), typeof(int) );
					

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:109:4: ^( DECLARATION TYPE_FLOAT v= ID )
				{
				DebugLocation(109, 4);
				DebugLocation(109, 6);
				Match(input,DECLARATION,Follow._DECLARATION_in_declaration398); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(109, 18);
				Match(input,TYPE_FLOAT,Follow._TYPE_FLOAT_in_declaration400); 
				DebugLocation(109, 30);
				v=(CommonTree)Match(input,ID,Follow._ID_in_declaration404); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(109, 35);

						memory.AllocateStorage( (v!=null?v.Text:default(string)), typeof(float) );
					

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("declaration", 13);
			LeaveRule("declaration", 13);
			LeaveRule_declaration();
		}
		DebugLocation(112, 1);
		} finally { DebugExitRule(GrammarFileName, "declaration"); }
		return;

	}
	// $ANTLR end "declaration"

	partial void EnterRule_assignment();
	partial void LeaveRule_assignment();
	// $ANTLR start "assignment"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:114:1: assignment[List<Instruction> instructionStream] : ^( ASSIGNMENT v= ID exp= addSubExp[instructionStream] ) ;
	[GrammarRule("assignment")]
	private void assignment(List<Instruction> instructionStream)
	{
		EnterRule_assignment();
		EnterRule("assignment", 14);
		TraceIn("assignment", 14);
		CommonTree v = default(CommonTree);
		Value exp = default(Value);

		try { DebugEnterRule(GrammarFileName, "assignment");
		DebugLocation(114, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:115:2: ( ^( ASSIGNMENT v= ID exp= addSubExp[instructionStream] ) )
			DebugEnterAlt(1);
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:115:4: ^( ASSIGNMENT v= ID exp= addSubExp[instructionStream] )
			{
			DebugLocation(115, 4);
			DebugLocation(115, 6);
			Match(input,ASSIGNMENT,Follow._ASSIGNMENT_in_assignment422); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(115, 18);
			v=(CommonTree)Match(input,ID,Follow._ID_in_assignment426); 
			DebugLocation(115, 25);
			PushFollow(Follow._addSubExp_in_assignment430);
			exp=addSubExp(instructionStream);
			PopFollow();


			Match(input, TokenTypes.Up, null); 

			DebugLocation(115, 56);

					Value var = ProgramDef.Instance.SymbolTable[(v!=null?v.Text:default(string))];
					instructionStream.Add( new CopyInstruction(var, exp) );
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("assignment", 14);
			LeaveRule("assignment", 14);
			LeaveRule_assignment();
		}
		DebugLocation(119, 1);
		} finally { DebugExitRule(GrammarFileName, "assignment"); }
		return;

	}
	// $ANTLR end "assignment"

	partial void EnterRule_addSubExp();
	partial void LeaveRule_addSubExp();
	// $ANTLR start "addSubExp"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:121:1: addSubExp[List<Instruction> instructionStream] returns [Value ret] : (exp= mulDivExp[instructionStream] | ^( '+' lhs= mulDivExp[instructionStream] rhs= mulDivExp[instructionStream] ) | ^( '-' lhs= mulDivExp[instructionStream] rhs= mulDivExp[instructionStream] ) );
	[GrammarRule("addSubExp")]
	private Value addSubExp(List<Instruction> instructionStream)
	{
		EnterRule_addSubExp();
		EnterRule("addSubExp", 15);
		TraceIn("addSubExp", 15);
		Value ret = default(Value);


		Value exp = default(Value);
		Value lhs = default(Value);
		Value rhs = default(Value);

		try { DebugEnterRule(GrammarFileName, "addSubExp");
		DebugLocation(121, 3);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:122:2: (exp= mulDivExp[instructionStream] | ^( '+' lhs= mulDivExp[instructionStream] rhs= mulDivExp[instructionStream] ) | ^( '-' lhs= mulDivExp[instructionStream] rhs= mulDivExp[instructionStream] ) )
			int alt15=3;
			try { DebugEnterDecision(15, false);
			switch (input.LA(1))
			{
			case LITERAL:
			case PARENEXP:
			case UNARY:
			case VARIABLE:
			case 30:
			case 34:
				{
				alt15 = 1;
				}
				break;
			case 31:
				{
				alt15 = 2;
				}
				break;
			case 33:
				{
				alt15 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 15, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:122:5: exp= mulDivExp[instructionStream]
				{
				DebugLocation(122, 8);
				PushFollow(Follow._mulDivExp_in_addSubExp454);
				exp=mulDivExp(instructionStream);
				PopFollow();

				DebugLocation(122, 38);

						ret = exp;
					

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:125:7: ^( '+' lhs= mulDivExp[instructionStream] rhs= mulDivExp[instructionStream] )
				{
				DebugLocation(125, 7);
				DebugLocation(125, 9);
				Match(input,31,Follow._31_in_addSubExp466); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(125, 16);
				PushFollow(Follow._mulDivExp_in_addSubExp470);
				lhs=mulDivExp(instructionStream);
				PopFollow();

				DebugLocation(125, 49);
				PushFollow(Follow._mulDivExp_in_addSubExp475);
				rhs=mulDivExp(instructionStream);
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(125, 80);

				  		instructionStream.Add( new AddInstruction(lhs, rhs, ret) );
				  	

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:128:7: ^( '-' lhs= mulDivExp[instructionStream] rhs= mulDivExp[instructionStream] )
				{
				DebugLocation(128, 7);
				DebugLocation(128, 9);
				Match(input,33,Follow._33_in_addSubExp488); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(128, 16);
				PushFollow(Follow._mulDivExp_in_addSubExp492);
				lhs=mulDivExp(instructionStream);
				PopFollow();

				DebugLocation(128, 49);
				PushFollow(Follow._mulDivExp_in_addSubExp497);
				rhs=mulDivExp(instructionStream);
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(128, 80);

				  		instructionStream.Add( new SubtractInstruction(lhs, rhs, ret) );
				  	

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("addSubExp", 15);
			LeaveRule("addSubExp", 15);
			LeaveRule_addSubExp();
		}
		DebugLocation(131, 3);
		} finally { DebugExitRule(GrammarFileName, "addSubExp"); }
		return ret;

	}
	// $ANTLR end "addSubExp"

	partial void EnterRule_mulDivExp();
	partial void LeaveRule_mulDivExp();
	// $ANTLR start "mulDivExp"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:133:1: mulDivExp[List<Instruction> instructionStream] returns [Value ret] : (val= unaryExp[instructionStream] | ^( '*' lhs= unaryExp[instructionStream] rhs= unaryExp[instructionStream] ) | ^( '/' lhs= unaryExp[instructionStream] rhs= unaryExp[instructionStream] ) );
	[GrammarRule("mulDivExp")]
	private Value mulDivExp(List<Instruction> instructionStream)
	{
		EnterRule_mulDivExp();
		EnterRule("mulDivExp", 16);
		TraceIn("mulDivExp", 16);
		Value ret = default(Value);


		Value val = default(Value);
		Value lhs = default(Value);
		Value rhs = default(Value);

		try { DebugEnterRule(GrammarFileName, "mulDivExp");
		DebugLocation(133, 3);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:134:2: (val= unaryExp[instructionStream] | ^( '*' lhs= unaryExp[instructionStream] rhs= unaryExp[instructionStream] ) | ^( '/' lhs= unaryExp[instructionStream] rhs= unaryExp[instructionStream] ) )
			int alt16=3;
			try { DebugEnterDecision(16, false);
			switch (input.LA(1))
			{
			case LITERAL:
			case PARENEXP:
			case UNARY:
			case VARIABLE:
				{
				alt16 = 1;
				}
				break;
			case 30:
				{
				alt16 = 2;
				}
				break;
			case 34:
				{
				alt16 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 16, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(16); }
			switch (alt16)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:134:5: val= unaryExp[instructionStream]
				{
				DebugLocation(134, 8);
				PushFollow(Follow._unaryExp_in_mulDivExp522);
				val=unaryExp(instructionStream);
				PopFollow();

				DebugLocation(134, 37);

						ret = val;
					

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:137:7: ^( '*' lhs= unaryExp[instructionStream] rhs= unaryExp[instructionStream] )
				{
				DebugLocation(137, 7);
				DebugLocation(137, 9);
				Match(input,30,Follow._30_in_mulDivExp534); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(137, 16);
				PushFollow(Follow._unaryExp_in_mulDivExp538);
				lhs=unaryExp(instructionStream);
				PopFollow();

				DebugLocation(137, 48);
				PushFollow(Follow._unaryExp_in_mulDivExp543);
				rhs=unaryExp(instructionStream);
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(137, 78);

				  		instructionStream.Add( new MultiplyInstruction(lhs, rhs, ret) );
				  	

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:140:6: ^( '/' lhs= unaryExp[instructionStream] rhs= unaryExp[instructionStream] )
				{
				DebugLocation(140, 6);
				DebugLocation(140, 8);
				Match(input,34,Follow._34_in_mulDivExp555); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(140, 15);
				PushFollow(Follow._unaryExp_in_mulDivExp559);
				lhs=unaryExp(instructionStream);
				PopFollow();

				DebugLocation(140, 47);
				PushFollow(Follow._unaryExp_in_mulDivExp564);
				rhs=unaryExp(instructionStream);
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(140, 77);

				 		instructionStream.Add( new DivideInstruction(lhs, rhs, ret) );
				 	

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("mulDivExp", 16);
			LeaveRule("mulDivExp", 16);
			LeaveRule_mulDivExp();
		}
		DebugLocation(143, 3);
		} finally { DebugExitRule(GrammarFileName, "mulDivExp"); }
		return ret;

	}
	// $ANTLR end "mulDivExp"

	partial void EnterRule_unaryExp();
	partial void LeaveRule_unaryExp();
	// $ANTLR start "unaryExp"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:145:1: unaryExp[List<Instruction> instructionStream] returns [Value ret] : ( ^( UNARY v= value[instructionStream] ) |v= value[instructionStream] );
	[GrammarRule("unaryExp")]
	private Value unaryExp(List<Instruction> instructionStream)
	{
		EnterRule_unaryExp();
		EnterRule("unaryExp", 17);
		TraceIn("unaryExp", 17);
		Value ret = default(Value);


		Value v = default(Value);

		try { DebugEnterRule(GrammarFileName, "unaryExp");
		DebugLocation(145, 3);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:146:4: ( ^( UNARY v= value[instructionStream] ) |v= value[instructionStream] )
			int alt17=2;
			try { DebugEnterDecision(17, false);
			int LA17_1 = input.LA(1);

			if ((LA17_1==UNARY))
			{
				alt17 = 1;
			}
			else if ((LA17_1==LITERAL||LA17_1==PARENEXP||LA17_1==VARIABLE))
			{
				alt17 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 17, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(17); }
			switch (alt17)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:146:7: ^( UNARY v= value[instructionStream] )
				{
				DebugLocation(146, 7);
				DebugLocation(146, 9);
				Match(input,UNARY,Follow._UNARY_in_unaryExp591); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(146, 16);
				PushFollow(Follow._value_in_unaryExp595);
				v=value(instructionStream);
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(146, 43);

				  		if( v.ValueType == typeof(int) ) {
					  		instructionStream.Add( new SubtractInstruction(Value.IntZero, v, ret) );
					  	} else if( v.ValueType == typeof(float) ) {
					  		instructionStream.Add( new SubtractInstruction(Value.FloatZero, v, ret) );
					  	} else {
					  		// Throw invalid type exception
					  	}
				  	

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:155:5: v= value[instructionStream]
				{
				DebugLocation(155, 6);
				PushFollow(Follow._value_in_unaryExp607);
				v=value(instructionStream);
				PopFollow();

				DebugLocation(155, 32);

						ret = v;
					

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("unaryExp", 17);
			LeaveRule("unaryExp", 17);
			LeaveRule_unaryExp();
		}
		DebugLocation(158, 3);
		} finally { DebugExitRule(GrammarFileName, "unaryExp"); }
		return ret;

	}
	// $ANTLR end "unaryExp"

	partial void EnterRule_value();
	partial void LeaveRule_value();
	// $ANTLR start "value"
	// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:160:1: value[List<Instruction> instructionStream] returns [Value ret] : ( ^( VARIABLE v= ID ) | ^( LITERAL TYPE_INT i= INT ) | ^( LITERAL TYPE_FLOAT f= FLOAT ) | ^( PARENEXP e= addSubExp[instructionStream] ) );
	[GrammarRule("value")]
	private Value value(List<Instruction> instructionStream)
	{
		EnterRule_value();
		EnterRule("value", 18);
		TraceIn("value", 18);
		Value ret = default(Value);


		CommonTree v = default(CommonTree);
		CommonTree i = default(CommonTree);
		CommonTree f = default(CommonTree);
		Value e = default(Value);

		try { DebugEnterRule(GrammarFileName, "value");
		DebugLocation(160, 1);
		try
		{
			// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:161:2: ( ^( VARIABLE v= ID ) | ^( LITERAL TYPE_INT i= INT ) | ^( LITERAL TYPE_FLOAT f= FLOAT ) | ^( PARENEXP e= addSubExp[instructionStream] ) )
			int alt18=4;
			try { DebugEnterDecision(18, false);
			switch (input.LA(1))
			{
			case VARIABLE:
				{
				alt18 = 1;
				}
				break;
			case LITERAL:
				{
				int LA18_2 = input.LA(2);

				if ((LA18_2==DOWN))
				{
					int LA18_3 = input.LA(3);

					if ((LA18_3==TYPE_INT))
					{
						alt18 = 2;
					}
					else if ((LA18_3==TYPE_FLOAT))
					{
						alt18 = 3;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 18, 4, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 18, 2, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case PARENEXP:
				{
				alt18 = 4;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 18, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(18); }
			switch (alt18)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:161:4: ^( VARIABLE v= ID )
				{
				DebugLocation(161, 4);
				DebugLocation(161, 6);
				Match(input,VARIABLE,Follow._VARIABLE_in_value632); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(161, 16);
				v=(CommonTree)Match(input,ID,Follow._ID_in_value636); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(161, 21);

						try {
							ret = ProgramDef.Instance.SymbolTable[(v!=null?v.Text:default(string))];
						} catch( KeyNotFoundException ex ) {
							Console.Write( string.Format("Symbol {0} wasn't declared before use", (v!=null?v.Text:default(string))) );
						}
					

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:168:4: ^( LITERAL TYPE_INT i= INT )
				{
				DebugLocation(168, 4);
				DebugLocation(168, 6);
				Match(input,LITERAL,Follow._LITERAL_in_value645); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(168, 14);
				Match(input,TYPE_INT,Follow._TYPE_INT_in_value647); 
				DebugLocation(168, 24);
				i=(CommonTree)Match(input,INT,Follow._INT_in_value651); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(168, 30);

						ret = new LiteralValue(int.Parse((i!=null?i.Text:default(string))));
						
					

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:172:4: ^( LITERAL TYPE_FLOAT f= FLOAT )
				{
				DebugLocation(172, 4);
				DebugLocation(172, 6);
				Match(input,LITERAL,Follow._LITERAL_in_value660); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(172, 14);
				Match(input,TYPE_FLOAT,Follow._TYPE_FLOAT_in_value662); 
				DebugLocation(172, 26);
				f=(CommonTree)Match(input,FLOAT,Follow._FLOAT_in_value666); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(172, 34);
				 
						ret = new LiteralValue(float.Parse((f!=null?f.Text:default(string))));
					

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\Users\\zeano_000\\Dropbox\\NeoInterpreter\\NeoCompiler\\NeoTreePass2.g:175:4: ^( PARENEXP e= addSubExp[instructionStream] )
				{
				DebugLocation(175, 4);
				DebugLocation(175, 6);
				Match(input,PARENEXP,Follow._PARENEXP_in_value675); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(175, 16);
				PushFollow(Follow._addSubExp_in_value679);
				e=addSubExp(instructionStream);
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(175, 47);

						ret = e;
					

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("value", 18);
			LeaveRule("value", 18);
			LeaveRule_value();
		}
		DebugLocation(178, 1);
		} finally { DebugExitRule(GrammarFileName, "value"); }
		return ret;

	}
	// $ANTLR end "value"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _FILE_in_file54 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _script_in_file56 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _SCRIPT_in_script70 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _functionDefs_in_script72 = new BitSet(new ulong[]{0x0000000000200008UL});
		public static readonly BitSet _program_in_script75 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _SCRIPT_in_script86 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _program_in_script88 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _FUNCTION_DEFS_in_functionDefs104 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _functionDef_in_functionDefs106 = new BitSet(new ulong[]{0x0000000000002008UL});
		public static readonly BitSet _FUNCTION_DEF_in_functionDef131 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_functionDef135 = new BitSet(new ulong[]{0x0000000000080808UL});
		public static readonly BitSet _parameters_in_functionDef140 = new BitSet(new ulong[]{0x0000000000000808UL});
		public static readonly BitSet _body_in_functionDef148 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _FUNCTION_BODY_in_body166 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _statement_in_body169 = new BitSet(new ulong[]{0x0000000000001058UL});
		public static readonly BitSet _PARAMS_in_parameters188 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _param_in_parameters191 = new BitSet(new ulong[]{0x0000000000040008UL});
		public static readonly BitSet _PARAM_in_param210 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _TYPE_INT_in_param212 = new BitSet(new ulong[]{0x0000000000008000UL});
		public static readonly BitSet _ID_in_param216 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _PARAM_in_param225 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _TYPE_FLOAT_in_param227 = new BitSet(new ulong[]{0x0000000000008000UL});
		public static readonly BitSet _ID_in_param231 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _FUNCTION_CALL_in_functionCall256 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_functionCall260 = new BitSet(new ulong[]{0x0000000000000408UL});
		public static readonly BitSet _arguments_in_functionCall264 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _FUNCTION_ARGUMENTS_in_arguments284 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _argument_in_arguments287 = new BitSet(new ulong[]{0x0000000000000208UL});
		public static readonly BitSet _FUNCTION_ARGUMENT_in_argument306 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _value_in_argument310 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _PROGRAM_in_program333 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _statement_in_program336 = new BitSet(new ulong[]{0x0000000000001058UL});
		public static readonly BitSet _declaration_in_statement356 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _assignment_in_statement362 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _functionCall_in_statement368 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _DECLARATION_in_declaration383 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _TYPE_INT_in_declaration385 = new BitSet(new ulong[]{0x0000000000008000UL});
		public static readonly BitSet _ID_in_declaration389 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _DECLARATION_in_declaration398 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _TYPE_FLOAT_in_declaration400 = new BitSet(new ulong[]{0x0000000000008000UL});
		public static readonly BitSet _ID_in_declaration404 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _ASSIGNMENT_in_assignment422 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_assignment426 = new BitSet(new ulong[]{0x00000006C6120000UL});
		public static readonly BitSet _addSubExp_in_assignment430 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _mulDivExp_in_addSubExp454 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _31_in_addSubExp466 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _mulDivExp_in_addSubExp470 = new BitSet(new ulong[]{0x0000000446120000UL});
		public static readonly BitSet _mulDivExp_in_addSubExp475 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _33_in_addSubExp488 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _mulDivExp_in_addSubExp492 = new BitSet(new ulong[]{0x0000000446120000UL});
		public static readonly BitSet _mulDivExp_in_addSubExp497 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _unaryExp_in_mulDivExp522 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _30_in_mulDivExp534 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _unaryExp_in_mulDivExp538 = new BitSet(new ulong[]{0x0000000006120000UL});
		public static readonly BitSet _unaryExp_in_mulDivExp543 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _34_in_mulDivExp555 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _unaryExp_in_mulDivExp559 = new BitSet(new ulong[]{0x0000000006120000UL});
		public static readonly BitSet _unaryExp_in_mulDivExp564 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _UNARY_in_unaryExp591 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _value_in_unaryExp595 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _value_in_unaryExp607 = new BitSet(new ulong[]{0x0000000000000002UL});
		public static readonly BitSet _VARIABLE_in_value632 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _ID_in_value636 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _LITERAL_in_value645 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _TYPE_INT_in_value647 = new BitSet(new ulong[]{0x0000010000000000UL});
		public static readonly BitSet _INT_in_value651 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _LITERAL_in_value660 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _TYPE_FLOAT_in_value662 = new BitSet(new ulong[]{0x0000008000000000UL});
		public static readonly BitSet _FLOAT_in_value666 = new BitSet(new ulong[]{0x0000000000000008UL});
		public static readonly BitSet _PARENEXP_in_value675 = new BitSet(new ulong[]{0x0000000000000004UL});
		public static readonly BitSet _addSubExp_in_value679 = new BitSet(new ulong[]{0x0000000000000008UL});
	}
	#endregion Follow sets
}
